name: "Data Work Request"
description: "Template for requesting data-related work for the website"
labels: ["data-work"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Data Work Request
        Please fill out this form to request data-related work for the website.

  - type: dropdown
    id: data_content
    attributes:
      label: Data Content
      description: "What type of data content is involved?"
      multiple: true
      options:
        - Product
        - Pricing
        - Inventory
        - Analytics
        - Images
        - Descriptions
        - Other
    validations:
      required: true

  - type: dropdown
    id: product_type
    attributes:
      label: Product Type
      description: "What product types are involved?"
      multiple: true
      options:
        - Single Cards
        - Sealed Products
        - Accessories
        - Bundles
        - Digital Items
        - Other
    validations:
      required: true

  - type: dropdown
    id: product_brand
    attributes:
      label: Product Brand
      description: "Which product brands are involved?"
      multiple: true
      options:
        - Lorcana
        - MTG
        - Pokemon
        - One Piece
        - Flesh and Blood
        - Yu-Gi-Oh!
        - Digimon
        - Other
    validations:
      required: true

  - type: dropdown
    id: data_task
    attributes:
      label: Data Task
      description: "What type of data task is needed?"
      multiple: true
      options:
        - Refresh (Update existing data)
        - Add (New data entry)
        - Enhancement (Improve existing data)
        - Cleanup (Fix or standardize data)
        - Migration (Move data between systems)
        - Scraping (Collect data from external sources)
        - Analysis (Generate insights from data)
        - Export (Prepare data for external use)
    validations:
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: "Please provide details about what needs to be done."
      placeholder: "Example: Need to scrape current prices for all Lorcana single cards from competitor sites and update our pricing database."
    validations:
      required: true

  - type: textarea
    id: data_sources
    attributes:
      label: Data Sources
      description: "Where will the data come from? Include URLs if applicable."
      placeholder: "Example: https://example.com/prices, internal database, etc."
    validations:
      required: false

  - type: textarea
    id: expected_output
    attributes:
      label: Expected Output
      description: "What format should the final data be in? Where should it be stored/uploaded?"
      placeholder: "Example: CSV file uploaded to the shared Google Drive folder, direct database update, etc."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "How urgent is this data work?"
      options:
        - Critical (Blocking operations)
        - High (Needed within 24 hours)
        - Medium (Needed within the week)
        - Low (Nice to have)
    validations:
      required: true

  - type: dropdown
    id: estimated_effort
    attributes:
      label: Estimated Effort
      description: "How complex is this data work expected to be?"
      options:
        - Small (Less than 2 hours)
        - Medium (2-8 hours)
        - Large (1-3 days)
        - Extra Large (More than 3 days)
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: "Any other details that might be helpful for completing this task."
    validations:
      required: false
